- .storybook/preview.js
- src/components/video-caption/VideoCaption.vue
- stories/Article.stories.js
- stories/ImageWithCaption.stories.js
- stories/PageIntro.stories.js
- stories/Video.stories.js
Adds a couple of missing video stories including a way to display cookies on/off
> Fix video not appearing in article

- src/components/map-with-sidebar/MapWithSidebar.vue
- src/components/map-with-sidebar/components/MapWithSidebarPanel.vue
- src/components/map-with-sidebar/components/__tests__/MapWithSidebarPanel.jest.spec.js
- stories/MapWithSidebar.stories.js
> 308 fed replace card back button with menu button

- .storybook/main.cjs
- package.json
- src/utils/data-layer-templates.js
- yarn.lock
> 141 analytics video missing variables

- src/components/product-search/components/Autocomplete.vue
> 317 fed space not being removed from end of location name if added by mistake

- src/components/form/Form.vue
Updated to only get the hidden fields within the form rather than all hidden fields on the page.
> 594 implement newsletter signup form using bloomreach engage

- stories/Modal.stories.js
Meant to push this ages ago...
> feat(modal): add missing modal video story

- src/components/accordion/components/AccordionItem.vue
- src/components/itineraries/Itinerary.vue
- src/components/map-marker-icon/MapMarkerIcon.vue
- src/components/map-with-sidebar/components/MapWithSidebarCategory.vue
- src/components/map/components/MapMarker.vue
- src/components/mega-nav/components/MegaNavAccordionItem.vue
- src/components/mega-nav/components/MegaNavDropdown.vue
- src/styles/mixins/_map-button-themes.scss
- stories/Accordion.stories.js
Some code tidy and aligning current buttons to our system
> Ds 305 document unique button elements currently in the system

- src/components/accordion/components/AccordionToggle.vue
- src/components/banner/Banner.vue
- src/components/button/Button.vue
- src/components/button/__tests__/Button.jest.spec.js
- src/components/carbon-calculator/CarbonCalculator.vue
- src/components/heading/Heading.vue
- src/components/map-with-sidebar/components/MapWithSidebarButtons.vue
- src/components/map-with-sidebar/components/MapWithSidebarPanel.vue
- src/components/map/Map.vue
- src/components/mega-nav/MegaNav.vue
- src/components/mega-nav/components/MegaNavDropdown.vue
- src/components/mega-nav/components/MegaNavTopMenu.vue
- src/components/modal/Modal.vue
- src/components/product-search/components/GuestSelector.vue
- src/components/site-search/SiteSearch.vue
- src/components/site-search/components/SiteSearchForm.vue
- src/components/ski-scotland/ski-scotland-card/SkiScotlandCard.vue
- src/components/social-share/SocialShare.vue
- src/components/stretched-link-card/StretchedLinkCard.vue
- src/components/video-caption/VideoCaption.vue
- stories/Button.stories.js
- stories/Itinerary.stories.js
- stories/Tooltip.stories.js
Updating various buttons to be in line with new designs with more consistency.
> Ds 349 figma update exisiting components to use new buttons

- src/components/article/components/ArticleSidebar.vue
- src/components/article/components/__tests__/ArticleSidebar.jest.spec.js
- src/components/breadcrumb/Breadcrumb.vue
- src/components/button-toggle-group/ButtonToggleGroup.vue
- src/components/carbon-calculator/components/CarbonCalculatorTip.vue
- src/components/checkbox/Checkbox.vue
- src/components/footer/Footer.vue
- src/components/footer/components/FooterSocialMenu.vue
- src/components/link/Link.vue
- src/components/mega-nav/components/MegaNavDropdown.vue
- src/components/page-intro/PageIntro.vue
- src/components/panel/Panel.vue
- src/components/ski-scotland/ski-scotland-card/SkiScotlandCard.vue
- src/components/ski-scotland/ski-scotland-status/SkiScotlandStatus.vue
- src/components/social-credit-link/SocialCreditLink.vue
- src/components/summary-box/SummaryBoxList.vue
- src/styles/_bootstrap-overrides.scss
- src/styles/mixins/_vs-heading-style.scss
- src/styles/mixins/_vs-sub-heading-style.scss
- src/tokens/spacing.yml
- stories/Accordion.stories.js
- stories/List.stories.js
- stories/SkiScotlandCard.stories.js
- stories/SkiScotlandStatus.stories.js
- stories/Tabs.stories.js
> refactor(spacers): remove old spacer tokens from the codebase

- CHANGELOG.md
- package.json
- src/components/quote/Quote.vue
- stories/TourismInfo.stories.js
Removed the excess whitespace on the TourismInfo module.
Refactored the TourismInfo story as well.
> Ds 359 removal of white space from the local expert module on destination pages

- src/components/article/components/ArticleSidebar.vue
- src/components/article/components/__tests__/ArticleSidebar.jest.spec.js
- src/components/link-list/LinkList.vue
- stories/Article.stories.js
- stories/LinkList.stories.js
Add the table of contents (link list) component to the article sidebar for the BSH site
> Ds 345 place table of contents on general page

- src/components/button/Button.vue
- src/components/ski-scotland/ski-scotland-status/SkiScotlandStatus.vue
- src/components/ski-scotland/ski-scotland-status/__tests__/SkiScotlandStatus.jest.spec.js
- src/styles/_placeholders.scss
- src/tokens/color-background.yml
- src/tokens/color-border.yml
- src/tokens/color-icons.yml
- src/tokens/color-interaction.yml
- src/tokens/color-text.yml
- src/tokens/primitives/color-support-primitives.yml
Adding these into the codebase before I then make a start replacing all the old ones and removing them.
> style(tokens): add new colour palette tokens into frontend codebase

- src/components/itineraries/components/ItineraryStop.vue
- stories/Itinerary.stories.js
Added a slot for the time to explore information and linked accordingly.
> fix(itinerary): time to Explore information moved to correct place from design

- src/components/article/components/ArticleSidebar.vue
- src/components/article/components/__tests__/ArticleSidebar.jest.spec.js
- src/components/badge/VsBadge.vue
- src/components/page-intro/PageIntro.vue
- src/components/page-intro/__tests__/pageintro.jest.spec.js
- stories/Article.stories.js
- stories/PageIntro.stories.js
Due to miscommunication the table of contents needs to be moved from the article sidebar to the page intro component.
> Ds 345 add toc to pageintro

- src/components/form/Form.vue
- src/components/form/__tests__/Form.jest.spec.js
fix(form.vue): modify form logic to handle and correct malformed JSON payload
After identifying a bug where the Form was sending data in a malformed JSON structure to BREG, changes were made to ensure proper data formatting and submission.
DS-818
> DS-818 - Modify form logic to handle and correct malformed JSON payload sent to BREG

- src/components/back-to-top/BackToTop.vue
Changing when the event listener is added as it's currently causing an error on BSH.
> DS-749 Back to top 3

- src/components/back-to-top/BackToTop.vue
Another fix of the back to top component, I've tested this using Yarn link so hopefully this is the last one.
> DS-749 Back to top 4

- src/assets/fixtures/maps/places-data-regional-no-icentres.json
- src/components/button-toggle-group/ButtonToggleGroup.vue
- src/components/map-with-sidebar/MapWithSidebar.vue
- src/components/map-with-sidebar/components/MapWithSidebarPanel.vue
- stories/MapWithSidebar.stories.js
Ignore the revert (revert) commits, I definitely didn't push this direct to main first by accident
> Hide toggles and filters that don't correlate to any locations (icentre closures)

- src/components/event-card/EventCard.vue
- src/components/event-card/__tests__/EventCard.jest.spec.js
- src/components/event-card/index.js
- src/components/index.ts
- stories/EventCard.stories.js
> Ds 909 fed events create the cards to display the event listings

- src/components/carousel/components/CarouselSlide.vue
- src/components/img/Img.vue
- src/components/itineraries/components/ItineraryStop.vue
- src/components/listicle/ListicleItem.vue
- src/styles/mixins/_vs-sub-heading-style.scss
Subheading styles that are left will be addressed separately
> Ds 1028 decouple heading and sub heading design component

- src/components/tabs/Tabs.vue
Make sure all tabs are the same height on mobile
> BSHUB-710 Training tab height when other tabs wrap

- src/components/link/__tests__/Link.jest.spec.js
- src/components/site-search/components/SiteSearchForm.vue
- src/components/ski-scotland/ski-scotland-status/SkiScotlandStatus.vue
> Ds 1320 remove deprecated clear button text prop from input component
