visitscotland/vs-component-library

package.json
src/components/product-search/components/Autocomplete.vue
src/components/product-search/components/ProductSearchEmbed.vue
src/components/product-search/components/__tests__/Autocomplete.jest.spec.js
yarn.lock

The `vue3-simple-typeahead`  component has an accessibility issue where the options are read out, by a screen reader, as "Blank" when using the keyboard to navigation through the list of options. I've replaced this component with a `@headlessui/vue` component, which is accessible.

336 psw location options being read aloud as blank

---

.yarnrc.yml

Add npmPublishAccess setting to the .yarnrc.yml - this setting is required for publishing the package to NPM

Add npmPublishAccess setting

---

src/components/form/Form.vue
src/components/form/__tests__/Form.jest.spec.js
stories/Form.stories.js

The new newsletter sign up form requires the use of hidden fields, the value of these fields are set within the CMS. I've added a slot to the form component to add these hidden fields to the form.

594 implement newsletter signup form using bloomreach engage

---

src/stores/video.store.ts
tsconfig.json

Those odd errors in the build for product search were coming from the type declaration generation stage of the vite export. That does mean they shouldn't have caused any concrete errors but they were making things marginally less type safe; and they were specific to the product search because it's the only set of components we have that are marked as being in typescript (although they're not very consistently typed) since their import from the external package.
The change to the tsconfig allows those to find things within the @ alias properly, and the change to the store fixes another issue which that then brought up with types in components using the video store

fix(typescript): fix declaration generation error with aliases

---

src/components/product-search/components/ProductSearchEmbed.vue

re #589
Set the `locprox` value to zero since the search results includes items that are outwith the expected search area (e.g. places in Kinross showing up when searching Dunfermline).

589 se product search results returning incorrect things to do results for dunfermline

---

yarn.lock

Looks like there was some missing dependency updates as part of the upgrade to bootstrap-vue-next@0.17.0, which may have caused some style breakages on .com. This PR adds those missing dependency versions to the yarn.lock file.

NON-JIRA missing yarn lock updates

---

src/components/button/Button.vue

Dynamic binding is done differently in Vue3, we need to set the attribute to `undefined` instead for `false`. I've updated the `aria-label`, `href`, and `tabindex` with this change.

VS-249 FED BREG Newsletter Form Subscribe Button Aria label incorrect

---

src/components/mega-nav/MegaNav.vue

Fixes a minor visual bug on business events, the search isn't present and there's an extra nav entry to fill the same space, but the empty search/mobile container overlaps onto the next row and pushes everything out of alignment. This brings it back in and should ensure that any similar issues in the future at least look right.

fix(meganav): ensure that meganav remains on baseline if it overflows

---

src/styles/_bootstrap-overrides.scss
src/tokens/spacing.yml

there's no namespace collision with the new token names, so they can be added alongside the originals to provide backwards compatibility until the old ones can be deprecated
DS-326, DS-327

feat(spacing.yml tokens and utils): add spacing tokens in new format

---

src/components/mega-nav/components/MegaNavDropdown.vue
src/components/site-search/components/SiteSearchForm.vue

Currently you can tab past the end of a meganav dropdown, continue along the main menu and then tab behind the open meganav producing some confusing results. The two options were either forcing the user to loop around inside the dropdown until you actually hit the close button, or auto closing it when you tab past the end of the nav (and off the close button, as the last item in it). The former option seems more confusing, especially for visually impaired users as it isn't clear why you're being looped around inside this box making no progress. The latter seems visually clear for people who can see the screen (as the nav closes and focus moves to the next meganav title) and intuitive for people who cannot, as they simply continue to progress through the navigation

feat(meganav): close dropdown when tabbing out of it

---

.github/workflows/chromatic.yml
src/components/button/Button.vue

Apols for the wall of text, tl;dr I think this change does all the things we planned for it to do when we caught up about it in the last UI dev chat
---
This change does seem to work as we wanted, it requires a little more manual attention than before but it should save some snapshots. When you first create a PR it runs the Chromatic action as desired (so in this case there were no changes and it passed). Pushing a change to the PR that creates a regression doesn't automatically run Chromatic so there is a mild risk that we can merge those commits, but we should be able to generally tell when you're pushing something that does or doesn't change the output, and whether or not there are going to be more changes before it's worth checking. If you then go into Actions and manually run …

Reduce Chromatic frequency

---

src/components/heading/Heading.vue
src/components/itineraries/components/ItineraryStop.vue
src/components/listicle/ListicleItem.vue
src/components/map-marker-icon/MapMarkerIcon.vue
src/components/map-with-sidebar/components/MapWithSidebarListItem.vue
src/components/product-search/ProductSearch.vue
src/components/rich-text-wrapper/RichTextWrapper.vue
src/components/stretched-link-card/StretchedLinkCard.vue
src/components/summary-box/components/SummaryBoxDistanceListItem.vue
src/components/summary-box/components/SummaryBoxListItem.vue
src/styles/_os-branding.scss
src/styles/_placeholders.scss
src/styles/third-party/_cludo-search-results.scss
src/tokens/font.yml
src/tokens/heading-size.yml

I've removed the old heading-size tokens and updated the font-family tokens to use the bootstrap font-family-base where appropriate. I didn't understand at first how that worked so have left some comments on the font-family token file. 
Have also removed places the font-family was being set but it was already inheriting the default font-family.

Ds 535 update global bootstrap heading styles and remove old tokens

---

src/components/skip-to/SkipTo.vue
src/components/skip-to/__tests__/SkipTo.jest.spec.js
stories/SkipTo.stories.js

We need to add Skip To to Business Events and the Business Support Hub, BE doesn't have a search, BSH I'm not sure about but this just makes that link optional

feat(skip to): add ability to remove search from skip to

---

src/components/form/Form.vue

This wasn't working consistently. This turns on an option to fire the identify event instantly, rather than waiting for the next bundled event which was sometimes not happening before the user left the site.

feat(engagement): adjust exponea.identify syntax to fire event immediately

---

src/components/modal/Modal.vue
src/components/video/Video.vue

Fixed the duration changing incorrectly when modal closed.
Caused by a re-render of the video player when the modal closed, removed this re-render and added a round function to the seconds count to ensure it doesn't display decimal places as seconds are passed in as full numbers.

Ds 282 play button displaying video duration incorrectly after closing the modal

---

src/components/social-share/SocialShare.vue

Just added an offset to the bootstrap popover component so that the share popover moves over on the screen, making it fully visible on mobile.

fix(socialshare): social share popover is now fully on screen when mobile layouts

---

src/components/form/Form.vue

This datalayer event is firing on the Marketo forms but not on the Bloomreach Engage ones

fix(forms): fire datalayer event on bloomreach form submit

---

src/utils/check-vendor-library.js

The `checkVendorLibrary` function has a 500ms delay. When there's a navigation event the new page can occasionally start loading during this delay so the event doesn't get added to the datalayer. I've set the initial timeout interval to zero so that the function runs instantly first time and then set the interval to 500ms when it loops.

VS-62 Investigate drop off in mega nav analytics logged

---

src/components/styled-list/components/StyledListItem.vue

Extend the decorative line between numbers in a numbered list so that it covers the last list item. Also removed the padding from the bottom of the last list item.

DS-787 Extend step by step line on last item to end of the copy

---

src/components/stretched-link-card/StretchedLinkCard.vue

This condition was added in response to an erroneous design

fix(stretchedlinkcard.vue): remove BSH-specific prop resolution

---

vite.config.mts

These deprecation warnings are a known issue with recent versions of bootstrap and node. Long term it looks like it'll take a significant rewrite within bootstrap to ditch some dependencies, for now the recommended solution is just to suppress them pending those fixes, as they're just distracting
https://github.com/twbs/bootstrap/issues/40962

fix(bootstrap): suppress deprecation warnings

---

src/components/img/Img.vue
src/components/stretched-link-card/StretchedLinkCard.vue
stories/MegalinksLinkList.stories.js

The scaler doesn't do anything with SVGs, creating some weird outcomes in stretched link cards
This prevents svg images from attempting to scale, and fixes the subsequent layout problems in those link lists

fix(megalinks): stop accessing scaler for SVGs and fix layout in stretched link cards

---

src/components/form/Form.vue
stories/Form.stories.js

As there's currently a processing error in the BREG layer for some sectors on BSH we've been asked to display an error for the form as a whole if something goes wrong on submission. Looking at it this system, it seems that we've always had a slot for this value and everything in place to render it but we've never set the boolean to true. The label for it also exists in the .com cms and is being passed into the form in ftl. That goes back to at least before we moved from the .com repo into the separate component library one. Does anyone know why? Is it just an incomplete feature or did we drop it for some reason?
In practice it's only going to appear if all the fields are correct and filled out but an error comes from the back end, which is rare outside of this particular circumstance.

Bshub 465 fed enquiries display error message to user

---

src/components/tabs/components/TabItem.vue
src/mixins/dataLayerMixin.js
src/utils/data-layer-templates.js

Added a datalayer event for tab clicks.
There was a requirement to specifically track the tab and eventCard components on the BSH events listing page so I've added a property to the `tabClickTemplate` and `externalLinkTemplate` datalayer templates for this. This property is set to "True" when these components have the `data-event-listing="True"` attribute,  which needs to be added on the BSH site. Not an ideal solution but couldn't think of another way for these components to know that there were on the events listing page.

BSHUB-536 Event listings tracking datalayer work

---

src/components/filter/components/VsFilterSection.vue

Removing the set width on the date picker used within the filter component as it is too narrow on Firefox

BSHUB-674 Horizontal scrollbar appears when screen width is 1400px

---

src/components/hero-section/HeroSection.vue

This id is currently present on the page intro but not the hero section, without it the skip doesn't point to page content properly

feat(skip to): add landmark id to hero section heading

---

src/components/mega-nav/__tests__/meganav.jest.spec.js
src/components/mega-nav/components/MegaNavDropdown.vue
src/components/mega-nav/components/MegaNavDropdownContainer.vue
src/components/mega-nav/components/MegaNavTopMenu.vue

The accessibility issue on BSH was caused by a mixture of static and non-static menu items in the meganav. I've adjusted the aria roles so that they should now be correct when the meganav is static, non-static or mixed.

BSHUB-643 Accessibility MegaNav list items are not semantic

---

.storybook/main.ts
package.json
yarn.lock

This addon has been updated quite quickly so have added it back

chore(storybook): add datawatcher addon back to storybook

---

src/components/event-card/EventCard.vue
src/components/ski-scotland/ski-scotland-card/SkiScotlandCard.vue

These css rules are slightly incorrect (align-self takes center rather than middle and it should be a single : rather than :: for nth-child). While real browsers just sensibly ignore them and render around them, the browserstack visual testing tool Percy that QA use seems to have updated and now it completely crashes when it encounters any CSS errors which is very sensible I'm sure, but it's a blocker for the QA automation work Corina is looking at.
I'm just removing them for now as they aren't currently active - the event card date looks like it's positioned in the right place anyway and the ski cards are never not in the first 3 children because they're each contained within a separate VsCol - but give me a shout if there's a reason to keep either of them

fix(css): remove css rules with syntax errors

---

package.json
src/components/stretched-link-card/StretchedLinkCard.vue

Unclear what has changed exactly but since the v5 update the setup timing here is causing some issues in the Nuxt sites. It works fine in freemarker.com but that's a whole other beast anyway. Most of our components load the stores on mount instead of setup and it doesn't seem to have any impact on how it actually works for the user.

Adjust VideoStore start timing in Stretched Link Card

---

package.json
vite.config.mts
yarn.lock

We want to update BSH and BE to Nuxt 3.16 to bring in some security updates flagged by Dependabot, but it has some build issues out of the component library. They appear to all be caused by this node polyfills library, from 3.16 on Nuxt has more robust, inbuilt polyfill-ing behaviour for Node defaults like `process` and keeping this in place causes conflicts where it tries to redefine values that are already there. Removing this appears to allow the whole build to work as expected when installing through yalc.

fix(build): remove node polyfills library from vite build for nuxt 3.16 compatibility

---

src/components/footer/components/FooterSocialItem.vue
src/components/footer/components/__tests__/FooterSocialItem.jest.spec.js
stories/Footer.stories.js

As we've switched to using the real fontawesome names for these icons, the default aria label has changed from "facebook link" to "fab fa-facebook link". This provides an option to set an override, and we can use the name of the social platform for that to return to the original more intuitive behaviour.
I thought we might be able to get away with just changing this by setting it in the website itself, but that sets a label on the li but not on the anchor, which doesn't work as expected unfortunately.

fix(footer social links): add aria label override functionality

---

src/styles/third-party/_cludo-search-results.scss

This arrow icon in search results is currently missing, because it's trying to retrieve it from the solid fontawesome set rather than the regular one. Setting this font weight ensures it looks to the correct set.

fix(search results): set font weight to ensure icon is visible

---

.github/CODEOWNERS

This is an experimental change - in theory this file should configure github to automatically add reviewers to all PRs made to this repo. Currently they're all universal so it'll request a review from all FEDs for any PR in here, which is a tiny thing but it'll save a few seconds of searching. It could also be configured to request specific reviewers for certain filetypes of folders, which could be more useful for something like dot com where we'd want to separate it between front and back end code. The repo can then be configured to require a review from someone who is specifically a code owner for that filetype or folder, rather than just anyone.
Mostly this is just to save time adding the same 4 reviewers to every PR though :)

feat(codeowners): add codeowners file
